download:
  output_dir: data/historical
pairs:
- logical_symbol: BTC/USDT
  long_exchange: binance
  short_exchange: gateio
time_service:
  end_time: 2026-01-24 19:49:32.462790
  interval: 60
  start_time: 2026-01-17 19:49:32.462770
