download:
  output_dir: data/historical
pairs:
- logical_symbol: BTC/USDT
  long_exchange: binance
  short_exchange: okx
time_service:
  end_time: 2026-01-23 20:42:00
  interval: 60
  start_time: 2026-01-23 20:32:00
